---
- hosts: all
  become: yes # permite que ejecute todo como sudo
  vars:
    ip_host: "{{ ip_address }}" ## capturo la ip que mandé con vagrant
    conf_net: " sudo ifconfig eth1 {{ ip_host }} "

  tasks:
   - name: 01 - Update repo
     raw: apt-get update

   - name: 02 - Upgrade system
     apt: upgrade=dist update_cache=yes

   - name: 03 - Download ifconfig tool
     shell: sudo apt-get install -y net-tools
     args:
      executable: /bin/bash

   - name: 04 - Configure Private IP
     shell: "{{ conf_net }}"
     args:
      executable: /bin/bash

   - name: 05 - Install docker packages ## instalo cosas usando loop
     apt:
       name: "{{ item }}"
       state: present
       update_cache: yes
     with_items:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
     tags:
       - docker

   - name: 06 - Add Docker s official GPG key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present
     tags:
       - docker

   - name: 07 - Verify that we have the key with the fingerprint
     apt_key:
       id: 0EBFCD88
       state: present
     tags:
       - docker

   - name: 08 - Set up the stable repository
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
       state: present
       update_cache: yes
     tags:
       - docker

   - name: 09 - Update apt packages
     apt:
       update_cache: yes
     tags:
       - docker

   - name: 10 - Install docker
     apt:
       name: docker-ce
       state: present
       update_cache: yes
     tags:
       - docker

   - name: 11- Install docker-compose
     apt:
       name: docker-compose=1.8.*
       state: present
       update_cache: yes
     tags:
       - docker
   - name: 12 - Start Docker-Compose
     shell: docker-compose up -d
     args:
      chdir: /vagrant/Docker/wordpress-compose/
      executable: /bin/bash
